INSERT INTO categorias (nome) VALUES
                                  ('Ação'),
                                  ('Aventura'),
                                  ('Animação'),
                                  ('Artes Marciais'),
                                  ('Biografia'),
                                  ('Comédia'),
                                  ('Comédia Romântica'),
                                  ('Comédia Dramática'),
                                  ('Crime'),
                                  ('Cult'),
                                  ('Documentário'),
                                  ('Drama'),
                                  ('Drama Policial'),
                                  ('Drama Histórico'),
                                  ('Épico'),
                                  ('Espionagem'),
                                  ('Faroeste'),
                                  ('Fantasia'),
                                  ('Ficção Científica'),
                                  ('Filme B'),
                                  ('Filme Catástrofe'),
                                  ('Filme de Guerra'),
                                  ('História'),
                                  ('Infantil'),
                                  ('Investigação'),
                                  ('LGBTQIA+'),
                                  ('Mistério'),
                                  ('Musical'),
                                  ('Natureza'),
                                  ('Noir'),
                                  ('Paródia'),
                                  ('Policial'),
                                  ('Política'),
                                  ('Reality Show'),
                                  ('Religioso'),
                                  ('Romance'),
                                  ('Romance de Época'),
                                  ('Romance Adolescente'),
                                  ('Show / Concerto'),
                                  ('Suspense'),
                                  ('Suspense Psicológico'),
                                  ('Terror'),
                                  ('Terror Psicológico'),
                                  ('Thriller'),
                                  ('Trash'),
                                  ('Viagem no Tempo'),
                                  ('Zumbi'),
                                  ('Cinema Nacional'),
                                  ('Cinema Europeu'),
                                  ('Cinema Asiático'),
                                  ('Cinema Latino-Americano');